const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand()}
const s={floor:1,hp:500,energy:100,ehp:350,def:false,intent:'attack'};
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active')}
function bars(){ehbar.style.width=Math.max(0,s.ehp/350*100)+'%';phbar.style.width=Math.max(0,s.hp/500*100)+'%';ehp.textContent=Math.max(0,s.ehp)+' / 350 HP';hp.textContent=Math.max(0,s.hp)+' / 500 HP';php.textContent=Math.max(0,s.hp);energy.textContent=s.energy;floor.textContent=s.floor;bfloor.textContent=s.floor}
function startRun(){s.floor=1;show('map');bars()}
function room(t){if(t==='fight'){s.ehp=350;s.hp=500;s.energy=100;s.intent=Math.random()<.25?'heavy':'attack';intent.textContent=s.intent==='heavy'?'⚠️ Тяжёлая атака: 80–110':'⚔️ Обычная атака: 35–50';log.textContent='Выбери действие.';bars();show('battle')}else{rewardText.textContent=t==='treasure'?'Ты находишь Клык Пустоты: +15 ATK и особый эффект.':'Старая статуя дарит 50 золота и восстанавливает силы.';show('reward')}}
function enemy(){let d=s.intent==='heavy'?95:42;if(s.def)d=Math.floor(d*.45);s.hp-=d;s.def=false;s.energy=Math.min(100,s.energy);s.intent=Math.random()<.25?'heavy':'attack';intent.textContent=s.intent==='heavy'?'⚠️ Тяжёлая атака: 80–110':'⚔️ Обычная атака: 35–50';bars();if(s.hp<=0){log.textContent='Ты пал. Забег завершён.';setTimeout(()=>show('home'),900)}}
function act(a){let d=0;if(a==='attack'){d=50;s.energy=Math.min(100,s.energy+10)}if(a==='defend'){s.def=true;s.energy=Math.min(100,s.energy+15);log.textContent='Ты готовишься к удару.';bars();setTimeout(enemy,450);return}if(a==='sunder'){if(s.energy<25){log.textContent='Недостаточно энергии.';return}s.energy-=25;d=90}if(a==='steel'){if(s.energy<30){log.textContent='Недостаточно энергии.';return}s.energy-=30;s.def=true;d=25}s.ehp-=d;log.textContent='Ты наносишь '+d+' урона.';bars();if(s.ehp<=0){rewardText.textContent='Страж побеждён. Получен новый предмет.';show('reward')}else setTimeout(enemy,450)}
function continueRun(){s.floor++;show('map');bars()}
if(tg?.initDataUnsafe?.user){const u=tg.initDataUnsafe.user;user.textContent='Игрок: '+(u.first_name||'')+(u.username?' · @'+u.username:'')}else user.textContent='Режим предпросмотра'